plugins:
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Rails/ThreeStateBooleanColumn:
  Enabled: true
