inherit_gem: {}

plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/**/*'

Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/**/*'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'db/queue_schema.rb'
    - 'spec/**/*'

Lint/ShadowingOuterLocalVariable:
  Enabled: true
