---
openapi: 3.0.1
info:
  title: API V1
  version: v1
servers:
- url: http://localhost:3000
  description: Local dev server
paths:
  "/api/v1/user/check_status":
    post:
      summary: check_status
      tags:
      - Users
      parameters:
      - name: CF-IPCountry
        in: header
        required: true
        description: Country code from Cloudflare
        example: US
        schema:
          type: string
      responses:
        '200':
          description: successful
        '400':
          description: missing CF-IPCountry header
        '422':
          description: missing rooted_device param
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                idfa:
                  type: string
                  example: 8264148c-be95-4b2b-b260-6ee98dd53bf6
                rooted_device:
                  type: boolean
                  example: false
              required:
              - idfa
              - rooted_device
