default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: playvalve_api_development

test:
  <<: *default
  database: playvalve_api_test

production:
  <<: *default
  database: playvalve_api_production
